### ISSUE TITLE
🎯 What can I work on ? (old cordova app)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-cordova-app#92]
### What

- This app used to be the official Open Food Facts app between 2012 and 2019. 
- It is still deployed on the Apple App Store as Open Beauty Facts: https://github.com/openfoodfacts/openbeautyfacts-cordova-app/
- We should provide an update to Open Beauty Facts, with a customized version of https://github.com/openfoodfacts/smooth-app and archive this repo

### Tasks to sublimate this deprecated codebase
- [ ] Refresh the dependancies
- [ ] Ensure all features still work
- [ ] Start using the https://github.com/openfoodfacts/openfoodfacts-js plugin for network operations
- [ ] Turn it into a cordova plugin for 3rd party apps to use
